services:
  db:
    image: "postgres:16"
    environment:
      - POSTGRES_PASSWORD=lab2pass
      - POSTGRES_USER=natalia
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/01_init.sql
      - ./db/dim_modeling.sql:/docker-entrypoint-initdb.d/02_dim_modeling.sql
      - ./db/sql_analysis.sql:/docker-entrypoint-initdb.d/03_sql_analysis.sql

    ports:
      - "5432:5432"

  etl:
    container_name: lab2_etl
    restart: always
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db

volumes:
  db_data: